import matplotlib.pyplot as plt
import io
import pandas as pd
from datetime import datetime

def generate_health_report(diag_data: dict) -> bytes:
    """
    Generates a PDF report using matplotlib and returns it as a bytes object.
    """
    vin = diag_data.get('vin', 'UNKNOWN')
    health_score = diag_data.get('health_score', 0)
    health_grade = diag_data.get('health_grade', 'N/A')
    health_status = diag_data.get('health_status', 'Unknown')
    issues = diag_data.get('issues', [])
    predictions = diag_data.get('predictions', [])
    
    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.axis('off')
    
    # Title
    plt.text(0.5, 0.95, "BCScanTool - Vehicle Health Report", fontsize=20, ha='center', weight='bold')
    plt.text(0.5, 0.91, f"Report Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", fontsize=12, ha='center')
    plt.text(0.5, 0.88, f"VIN: {vin}", fontsize=12, ha='center', color='blue')
    
    # Overall Health
    plt.text(0.1, 0.80, "OVERALL HEALTH", fontsize=14, weight='bold', color='darkblue')
    plt.plot([0.1, 0.9], [0.79, 0.79], color='black', lw=1)
    
    plt.text(0.1, 0.75, f"Health Score: {health_score}/100", fontsize=12)
    plt.text(0.5, 0.75, f"Grade: {health_grade}", fontsize=12, weight='bold')
    plt.text(0.1, 0.71, f"Status: {health_status}", fontsize=12)
    
    # Issues
    plt.text(0.1, 0.64, "CURRENT DIAGNOSTIC ISSUES", fontsize=14, weight='bold', color='darkblue')
    plt.plot([0.1, 0.9], [0.63, 0.63], color='black', lw=1)
    
    y_pos = 0.59
    if not issues:
        plt.text(0.1, y_pos, "No active issues detected.", fontsize=11, color='green')
        y_pos -= 0.04
    else:
        for iss in issues[:6]: # Limit to top 6
            color = 'red' if iss.get('severity') == 'CRITICAL' else 'darkorange'
            plt.text(0.1, y_pos, f"[{iss.get('severity', 'INFO')}] {iss.get('issue', 'Issue')}", fontsize=11, weight='bold', color=color)
            y_pos -= 0.03
            details = str(iss.get('details', ''))
            plt.text(0.12, y_pos, details[:90] + ('...' if len(details)>90 else ''), fontsize=10)
            y_pos -= 0.04
            
    # Predictions
    y_pos -= 0.02
    plt.text(0.1, y_pos, "PREDICTIVE MAINTENANCE ALERTS", fontsize=14, weight='bold', color='darkblue')
    y_pos -= 0.01
    plt.plot([0.1, 0.9], [y_pos, y_pos], color='black', lw=1)
    y_pos -= 0.04
    
    if not predictions:
        plt.text(0.1, y_pos, "No impending failures predicted.", fontsize=11, color='green')
    else:
        for pred in predictions[:6]:
            plt.text(0.1, y_pos, f"[{pred.get('severity', 'INFO')}] {pred.get('issue', '')}", fontsize=11, weight='bold', color='purple')
            y_pos -= 0.03
            plt.text(0.12, y_pos, f"Prediction: {pred.get('prediction', '')} (Confidence: {pred.get('confidence', '')})", fontsize=10)
            y_pos -= 0.03
            details = str(pred.get('details', ''))
            plt.text(0.12, y_pos, details[:90] + ('...' if len(details)>90 else ''), fontsize=10)
            y_pos -= 0.04
            
    # Footer
    plt.text(0.5, 0.05, "Generated by BCScanTool Predictive AI System", fontsize=10, ha='center', style='italic', color='gray')
    
    buf = io.BytesIO()
    plt.savefig(buf, format='pdf', bbox_inches='tight')
    plt.close(fig)
    buf.seek(0)
    return buf.getvalue()
