from fpdf import FPDF
from datetime import datetime

class DiagnosticPDF(FPDF):
    def header(self):
        # Draw a beautiful top deep navy blue banner
        self.set_fill_color(22, 54, 87)  # Deep premium navy
        self.rect(0, 0, 210, 20, 'F')
        
        # Add a subtle highlight accent bar underneath
        self.set_fill_color(0, 123, 255)  # Tech Blue
        self.rect(0, 20, 210, 2, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 12)
        # Center aligned title in the banner
        self.set_y(5)
        self.cell(0, 10, 'BCScanTool - Predictive Maintenance Diagnostics', 0, 0, 'C')
        self.set_y(25)  # Reset y-coordinate for page content

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by BCScanTool AI Engine | Date: {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 0, 'C')

def generate_health_report(diag_data: dict) -> bytes:
    """
    Generates a professional, premium PDF report using fpdf2 and returns it as a bytes object.
    Bypasses slow matplotlib rendering and font-cache issues.
    """
    vin = diag_data.get('vin', 'UNKNOWN')
    health_score = diag_data.get('health_score', 0)
    health_grade = diag_data.get('health_grade', 'N/A')
    health_status = diag_data.get('health_status', 'Unknown')
    issues = diag_data.get('issues', [])
    predictions = diag_data.get('predictions', [])
    
    # Extract make and model if available in diag_data
    vehicle_info = "VEHICLE HEALTH REPORT"
    if 'make' in diag_data and 'model' in diag_data:
        vehicle_info = f"{diag_data.get('year', '')} {diag_data.get('make', '')} {diag_data.get('model', '')}".strip().upper()
    
    pdf = DiagnosticPDF()
    pdf.set_margins(15, 25, 15)  # Generous margins for premium print layout
    pdf.add_page()
    
    pdf.ln(5)
    
    # Header Info Table-style block
    pdf.set_text_color(33, 37, 41)
    pdf.set_font('Helvetica', 'B', 18)
    pdf.cell(0, 10, vehicle_info, 0, 1, 'L')
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(0, 6, f'VIN: {vin}', 0, 1, 'L')
    pdf.ln(5)
    
    # -------------------------------------------------------------
    # 1. Premium Health Score & Status Panel
    # -------------------------------------------------------------
    pdf.set_fill_color(248, 249, 250)  # Sleek warm white / grey background
    pdf.rect(15, 52, 180, 32, 'F')
    
    # Title
    pdf.set_xy(20, 55)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(50, 4, 'VEHICLE HEALTH SCORE', 0, 0, 'L')
    
    pdf.set_xy(20, 60)
    pdf.set_font('Helvetica', 'B', 24)
    # Color-code health score
    if health_score >= 90:
        pdf.set_text_color(40, 167, 69)  # Dynamic Green
    elif health_score >= 70:
        pdf.set_text_color(255, 140, 0)  # Dynamic Warning Amber
    else:
        pdf.set_text_color(220, 53, 69)  # Dynamic Critical Red
    pdf.cell(50, 12, f'{health_score}/100', 0, 0, 'L')
    
    # Grade Panel
    pdf.set_xy(80, 55)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(30, 4, 'GRADE', 0, 0, 'L')
    
    pdf.set_xy(80, 60)
    pdf.set_font('Helvetica', 'B', 24)
    # Match color with health score
    if health_score >= 90:
        pdf.set_text_color(40, 167, 69)
    elif health_score >= 70:
        pdf.set_text_color(255, 140, 0)
    else:
        pdf.set_text_color(220, 53, 69)
    pdf.cell(30, 12, f'{health_grade}', 0, 0, 'L')
    
    # Status Description
    pdf.set_xy(115, 55)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(108, 117, 125)
    pdf.cell(75, 4, 'STATUS DESCRIPTION', 0, 0, 'L')
    
    pdf.set_xy(115, 60)
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(51, 51, 51)
    pdf.multi_cell(75, 4.5, health_status)
    
    # Reset cursor position
    pdf.set_xy(15, 90)
    pdf.ln(5)
    
    # -------------------------------------------------------------
    # 2. Issues Section (DTCs)
    # -------------------------------------------------------------
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(22, 54, 87)
    pdf.cell(0, 8, 'CURRENT SYSTEM TROUBLE CODES (DTCS)', 0, 1, 'L')
    
    # Technical separator line
    pdf.set_draw_color(22, 54, 87)
    pdf.set_line_width(0.5)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    if not issues:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(40, 167, 69)
        pdf.cell(0, 8, '  [OK] No active Diagnostic Trouble Codes detected in this scan.', 0, 1, 'L')
        pdf.ln(3)
    else:
        for idx, iss in enumerate(issues[:8]):  # Show up to top 8 issues
            if pdf.get_y() > 255:
                pdf.add_page()
                pdf.ln(5)
                
            severity = iss.get('severity', 'INFO').upper()
            issue_title = iss.get('issue', 'DTC Fault')
            details = iss.get('details', '')
            
            # Severity Tag box styling
            pdf.set_font('Helvetica', 'B', 9)
            if severity == 'CRITICAL':
                pdf.set_fill_color(255, 235, 235)  # Light Red
                pdf.set_text_color(220, 53, 69)
                border_color = (220, 53, 69)
            elif severity == 'WARNING':
                pdf.set_fill_color(255, 243, 205)  # Light Amber
                pdf.set_text_color(133, 100, 4)
                border_color = (255, 193, 7)
            else:
                pdf.set_fill_color(230, 242, 255)  # Light Blue
                pdf.set_text_color(0, 102, 204)
                border_color = (0, 123, 255)
            
            # Draw tiny colored severity badge
            tag_text = f" {severity} "
            pdf.set_draw_color(*border_color)
            pdf.set_line_width(0.2)
            pdf.cell(24, 6, tag_text, 1, 0, 'C', fill=True)
            
            # Issue title
            pdf.set_x(43)
            pdf.set_font('Helvetica', 'B', 10.5)
            pdf.set_text_color(33, 37, 41)
            pdf.cell(0, 6, issue_title, 0, 1, 'L')
            
            # Details description
            pdf.set_font('Helvetica', '', 9.5)
            pdf.set_text_color(100, 110, 120)
            pdf.set_x(43)
            pdf.multi_cell(0, 4.5, details)
            pdf.ln(3)
            
    pdf.ln(5)
    
    # -------------------------------------------------------------
    # 3. Predictive AI Maintenance Alerts
    # -------------------------------------------------------------
    pdf.set_font('Helvetica', 'B', 13)
    pdf.set_text_color(22, 54, 87)
    pdf.cell(0, 8, 'PREDICTIVE DEEP LEARNING MAINTENANCE FORECASTS', 0, 1, 'L')
    
    # Separator line
    pdf.set_draw_color(22, 54, 87)
    pdf.set_line_width(0.5)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)
    
    if not predictions:
        pdf.set_font('Helvetica', 'I', 10)
        pdf.set_text_color(40, 167, 69)
        pdf.cell(0, 8, '  [OK] No component degradation anomalies predicted by the AI model.', 0, 1, 'L')
    else:
        for pred in predictions[:6]:
            if pdf.get_y() > 255:
                pdf.add_page()
                pdf.ln(5)
                
            issue_title = pred.get('issue', 'Anomalous Component')
            confidence = pred.get('confidence', 'High')
            prediction = pred.get('prediction', 'Immediate')
            details = pred.get('details', '')
            
            # Prognosis Purple Badge
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_fill_color(243, 230, 255)  # Light Purple
            pdf.set_text_color(111, 66, 193)  # Tech Purple
            pdf.set_draw_color(111, 66, 193)
            pdf.set_line_width(0.2)
            pdf.cell(24, 6, " PROGNOSIS ", 1, 0, 'C', fill=True)
            
            # Title
            pdf.set_x(43)
            pdf.set_font('Helvetica', 'B', 10.5)
            pdf.set_text_color(33, 37, 41)
            pdf.cell(0, 6, issue_title, 0, 1, 'L')
            
            # Timeframe and confidence metrics
            pdf.set_x(43)
            pdf.set_font('Helvetica', 'B', 8.5)
            pdf.set_text_color(111, 66, 193)
            pdf.cell(0, 4, f"FAIL TIMEFRAME: {prediction.upper()}  |  AI CONFIDENCE: {confidence.upper()}", 0, 1, 'L')
            
            # Prediction details
            pdf.set_font('Helvetica', '', 9.5)
            pdf.set_text_color(100, 110, 120)
            pdf.set_x(43)
            pdf.multi_cell(0, 4.5, details)
            pdf.ln(3)

    return bytes(pdf.output())
